import { Link } from '@inertiajs/react';
import { ArrowRight, Plus } from 'lucide-react';
import AppLayout from '../../layouts/AppLayout';

type Memo = { id: number; memo_number: string; title: string; classification: string; requires_acknowledgement: boolean; published_at: string; recipients_count: number; issuer: { name: string }; issuing_department: { name: string; short_name?: string } };

export default function Index({ memoranda, canPublish }: { memoranda: Memo[]; canPublish: boolean }) {
    return <AppLayout title="Memoranda"><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Central issuance</div><h1 className="mt-2 text-3xl font-bold text-slate-950">Memoranda</h1><p className="mt-2 text-sm text-slate-500">Municipal memoranda delivered to the appropriate employees and offices.</p></div>{canPublish && <Link href="/memoranda/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0b2852] px-4 py-3 text-sm font-semibold text-white"><Plus size={17} /> Publish memorandum</Link>}</div><div className="divide-y divide-slate-100 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{memoranda.map((memo) => <Link key={memo.id} href={`/memoranda/${memo.id}`} className="flex flex-col gap-4 px-6 py-5 transition hover:bg-blue-50/40 md:flex-row md:items-center md:justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-blue-700">{memo.memo_number}</div><div className="mt-1 text-lg font-semibold text-slate-950">{memo.title}</div><div className="mt-1 text-sm text-slate-500">{memo.issuing_department.short_name || memo.issuing_department.name} · {new Date(memo.published_at).toLocaleString()}</div></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold uppercase text-slate-700">{memo.classification}</span>{canPublish && <span className="text-xs text-slate-500">{memo.recipients_count} recipients</span>}<ArrowRight size={18} className="text-slate-400" /></div></Link>)}{memoranda.length === 0 && <div className="p-10 text-center text-sm text-slate-500">No memoranda available.</div>}</div></div></AppLayout>;
}
