import { Link, router } from '@inertiajs/react';
import { CheckCircle2 } from 'lucide-react';
import AppLayout from '../../layouts/AppLayout';

type Memo = { id: number; memo_number: string; title: string; body: string; classification: string; requires_acknowledgement: boolean; published_at: string; issuer: { name: string }; issuing_department: { name: string; short_name?: string } };
type Recipient = { viewed_at?: string | null; acknowledged_at?: string | null } | null;

export default function Show({ memorandum: memo, recipient, statistics }: { memorandum: Memo; recipient: Recipient; statistics: null | { delivered: number; viewed: number; acknowledged: number } }) {
    return <AppLayout title={memo.memo_number}><div className="mx-auto max-w-4xl space-y-6"><Link href="/memoranda" className="text-sm font-semibold text-blue-700">← Back to Memoranda</Link><article className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm md:p-10"><div className="border-b border-slate-100 pb-6"><div className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">{memo.memo_number}</div><h1 className="mt-3 text-3xl font-bold text-slate-950">{memo.title}</h1><div className="mt-3 text-sm text-slate-500">Issued by {memo.issuing_department.short_name || memo.issuing_department.name} · {new Date(memo.published_at).toLocaleString()}</div></div><div className="whitespace-pre-wrap py-8 text-[15px] leading-7 text-slate-700">{memo.body}</div>{recipient && memo.requires_acknowledgement && <div className="border-t border-slate-100 pt-6">{recipient.acknowledged_at ? <div className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><CheckCircle2 size={18} /> Acknowledged {new Date(recipient.acknowledged_at).toLocaleString()}</div> : <button onClick={() => router.post(`/memoranda/${memo.id}/acknowledge`)} className="rounded-xl bg-[#0b2852] px-5 py-3 text-sm font-semibold text-white">I acknowledge receipt</button>}</div>}</article>{statistics && <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="text-xs font-bold uppercase text-slate-500">Delivered</div><div className="mt-2 text-3xl font-bold text-slate-950">{statistics.delivered}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="text-xs font-bold uppercase text-slate-500">Viewed</div><div className="mt-2 text-3xl font-bold text-slate-950">{statistics.viewed}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="text-xs font-bold uppercase text-slate-500">Acknowledged</div><div className="mt-2 text-3xl font-bold text-slate-950">{statistics.acknowledged}</div></div></section>}</div></AppLayout>;
}
