import { Link } from '@inertiajs/react';
import { ArrowRight, Plus } from 'lucide-react';
import AppLayout from '../../layouts/AppLayout';

type Tx = { id: number; reference_no: string; title: string; transaction_type: string; priority: string; status: string; created_at: string; origin_department: { name: string; short_name?: string }; current_department: { name: string; short_name?: string } };

export default function Index({ transactions }: { transactions: Tx[] }) {
    return <AppLayout title="My Work"><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Inter-office workflow</div><h1 className="mt-2 text-3xl font-bold text-slate-950">Transactions</h1><p className="mt-2 text-sm text-slate-500">Incoming, outgoing, and routed municipal work visible to your authorized office.</p></div><Link href="/transactions/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0b2852] px-4 py-3 text-sm font-semibold text-white"><Plus size={17} /> New transaction</Link></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="hidden grid-cols-[150px_1fr_150px_170px_130px_44px] gap-4 border-b border-slate-100 bg-slate-50 px-6 py-3 text-xs font-bold uppercase tracking-wide text-slate-500 md:grid"><div>Reference</div><div>Transaction</div><div>Origin</div><div>Current office</div><div>Status</div><div /></div><div className="divide-y divide-slate-100">{transactions.map((tx) => <Link key={tx.id} href={`/transactions/${tx.id}`} className="grid gap-3 px-5 py-5 transition hover:bg-blue-50/40 md:grid-cols-[150px_1fr_150px_170px_130px_44px] md:items-center md:gap-4 md:px-6"><div className="text-xs font-bold text-blue-700">{tx.reference_no}</div><div><div className="font-semibold text-slate-950">{tx.title}</div><div className="mt-1 text-xs uppercase tracking-wide text-slate-400">{tx.priority} priority</div></div><div className="text-sm text-slate-600">{tx.origin_department.short_name || tx.origin_department.name}</div><div className="text-sm text-slate-600">{tx.current_department.short_name || tx.current_department.name}</div><div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{tx.status.replaceAll('_', ' ')}</span></div><ArrowRight className="hidden text-slate-400 md:block" size={18} /></Link>)}{transactions.length === 0 && <div className="p-10 text-center text-sm text-slate-500">No transactions are visible to this workspace yet.</div>}</div></div></div></AppLayout>;
}
