import { Link } from '@inertiajs/react';
import { AlertTriangle, Building2, Download, FileBarChart, Printer } from 'lucide-react';
import AppLayout from '../../layouts/AppLayout';

type Summary = {
    activeTransactions: number; overdueTransactions: number; completedThisMonth: number; offices: number; employees: number;
    memoranda: number; memoDelivered: number; memoAcknowledged: number; municipalRecords: number; leavePending: number;
    attendanceEvents: number; operations: number; operationsOverdue: number; onboardingOpen: number; offboardingOpen: number;
    propertyAssets: number; propertyAssigned: number; propertyUnreconciled: number; payrollPeriod?: string | null; payrollEmployees: number; payrollNet: number;
};
type Workload = { code: string; office: string; employees: number; active: number; overdue: number };
type Aging = { id: number; reference: string; title: string; origin?: string; current?: string; responsible: string; status: string; due?: string | null; overdue: boolean; age: string };
type Props = { permissions: { executive: boolean; hr: boolean }; summary: Summary; departmentWorkload: Workload[]; transactionAging: Aging[]; operationsByType: Record<string, number>; recordsByType: Record<string, number> };

const money = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 0 }).format(value);

export default function ReportsIndex({ permissions, summary, departmentWorkload, transactionAging, operationsByType, recordsByType }: Props) {
    const ackRate = summary.memoDelivered > 0 ? Math.round((summary.memoAcknowledged / summary.memoDelivered) * 100) : 0;
    const exports = [
        ...(permissions.executive ? [['Department Workload','department-workload'],['Transaction Aging','transaction-aging'],['Operations Monitoring','operations']] : []),
        ['Employee Directory','employee-directory'],
        ...(permissions.hr ? [['Payroll Summary','payroll-summary']] : []),
    ];
    const topCards = [
        ['Active Work', summary.activeTransactions], ['Overdue', summary.overdueTransactions], ['Employees', summary.employees], ['Offices', summary.offices],
        ['Onboarding', summary.onboardingOpen], ['Offboarding', summary.offboardingOpen], ['Assets', summary.propertyAssets], ['Unreconciled', summary.propertyUnreconciled],
    ];

    return <AppLayout title="Reports"><div className="mx-auto max-w-7xl space-y-5">
        <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Phase 1 · M10</div><h1 className="mt-2 text-3xl font-bold">Municipal Reports & Operational Evidence</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Workflow, workforce, lifecycle, property, records, and operational evidence from the same internal source of truth.</p></div><button onClick={() => window.print()} className="inline-flex w-fit items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold"><Printer size={16}/>Print report</button></div></section>
        <section className="grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-8">{topCards.map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-[9px] font-bold uppercase text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold">{value}</div></div>)}</section>
        <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><div className="text-[9px] uppercase text-slate-400">Memo acknowledgement</div><div className="mt-2 text-2xl font-bold">{ackRate}%</div><div className="text-[10px] text-slate-500">{summary.memoAcknowledged} / {summary.memoDelivered}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-[9px] uppercase text-slate-400">Property assigned</div><div className="mt-2 text-2xl font-bold">{summary.propertyAssigned}</div><div className="text-[10px] text-slate-500">currently accountable assets</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-[9px] uppercase text-slate-400">Pending leave</div><div className="mt-2 text-2xl font-bold">{summary.leavePending}</div><div className="text-[10px] text-slate-500">awaiting HR action</div></div>{permissions.hr ? <div className="rounded-2xl border bg-white p-4"><div className="text-[9px] uppercase text-slate-400">{summary.payrollPeriod || 'Payroll'}</div><div className="mt-2 text-xl font-bold">{money(summary.payrollNet)}</div><div className="text-[10px] text-slate-500">{summary.payrollEmployees} records</div></div> : <div className="rounded-2xl border bg-white p-4"><div className="text-[9px] uppercase text-slate-400">Operations overdue</div><div className="mt-2 text-2xl font-bold">{summary.operationsOverdue}</div></div>}</section>
        <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Download size={17}/><h2 className="font-bold">Permission-scoped exports</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{exports.map(([label,report])=><a key={report} href={`/reports/export/${report}`} className="flex items-center justify-between rounded-xl border px-3 py-2.5 text-xs font-semibold hover:bg-blue-50"><span>{label}</span><Download size={14}/></a>)}</div></section>
        <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><div className="flex items-center gap-2"><Building2 size={16}/><h2 className="font-bold">Office workload</h2></div></div><div className="divide-y">{departmentWorkload.slice(0,14).map(o=><div key={o.code} className="flex items-center justify-between px-5 py-3"><div><div className="text-sm font-semibold">{o.office}</div><div className="text-[10px] text-slate-400">{o.employees} employees · {o.code}</div></div><div className="text-right"><div className="text-sm font-bold">{o.active} active</div><div className={o.overdue ? 'text-xs font-bold text-rose-700' : 'text-xs text-emerald-700'}>{o.overdue} overdue</div></div></div>)}</div></div><div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><div className="flex items-center gap-2"><FileBarChart size={16}/><h2 className="font-bold">Transaction aging</h2></div></div><div className="divide-y">{transactionAging.map(tx=><Link key={tx.id} href={`/transactions/${tx.id}`} className="block px-5 py-3 hover:bg-slate-50"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-bold text-blue-700">{tx.reference}</div><div className="mt-1 text-sm font-semibold">{tx.title}</div><div className="mt-1 text-[10px] text-slate-500">{tx.current} · {tx.responsible} · {tx.age}</div></div>{tx.overdue&&<span className="inline-flex items-center gap-1 rounded-full bg-rose-50 px-2 py-1 text-[9px] font-bold uppercase text-rose-700"><AlertTriangle size={10}/>overdue</span>}</div></Link>)}</div></div></section>
        <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="font-bold">Operational coverage</h2><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(operationsByType).map(([type,count])=><div key={type} className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] uppercase text-slate-400">{type.replaceAll('_',' ')}</div><div className="mt-1 text-xl font-bold">{count}</div></div>)}</div></div><div className="rounded-3xl border bg-white p-5"><h2 className="font-bold">Central records coverage</h2><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(recordsByType).map(([type,count])=><div key={type} className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] uppercase text-slate-400">{type.replaceAll('_',' ')}</div><div className="mt-1 text-xl font-bold">{count}</div></div>)}</div></div></section>
    </div></AppLayout>;
}
