import { Link } from '@inertiajs/react';
import { ArrowRight, Building2 } from 'lucide-react';
import AppLayout from '../layouts/AppLayout';

type Tx = { id: number; reference_no: string; title: string; status: string; priority: string; origin_department: { name: string; short_name?: string } };

export default function MayorOffice({ queue, stats }: { queue: Tx[]; stats: { forApproval: number; forReview: number; highPriority: number; total: number } }) {
    const cards = [['For Approval', stats.forApproval], ['For Review', stats.forReview], ['High Priority', stats.highPriority], ['Active Queue', stats.total]];
    return <AppLayout title="Mayor's Office"><div className="mx-auto max-w-7xl space-y-6"><section className="overflow-hidden rounded-3xl bg-[#0b2852] p-7 text-white shadow-xl md:p-9"><div className="flex items-center gap-3 text-blue-200"><Building2 size={22} /><span className="text-xs font-bold uppercase tracking-[0.22em]">Executive command queue</span></div><h1 className="mt-4 text-3xl font-bold md:text-4xl">Mayor's Office Review & Approval</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-100">Transactions routed by municipal departments arrive here with their prior office history preserved for review.</p></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-3 text-3xl font-bold text-slate-950">{value}</div></div>)}</section><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-bold text-slate-950">Items requiring executive attention</h2></div><div className="divide-y divide-slate-100">{queue.map((tx) => <Link key={tx.id} href={`/transactions/${tx.id}`} className="flex flex-col gap-4 px-6 py-5 transition hover:bg-blue-50/40 md:flex-row md:items-center md:justify-between"><div><div className="text-xs font-bold text-blue-700">{tx.reference_no}</div><div className="mt-1 font-semibold text-slate-950">{tx.title}</div><div className="mt-1 text-sm text-slate-500">Origin: {tx.origin_department.short_name || tx.origin_department.name}</div></div><div className="flex items-center gap-3"><span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold uppercase text-amber-800">{tx.status.replaceAll('_', ' ')}</span><ArrowRight size={18} className="text-slate-400" /></div></Link>)}{queue.length === 0 && <div className="p-10 text-center text-sm text-slate-500">No items currently require Mayor's Office review.</div>}</div></section></div></AppLayout>;
}
