import { Link, router } from '@inertiajs/react';
import { ArrowRight, Plus, Search } from 'lucide-react';
import { useState } from 'react';
import AppLayout from '../../layouts/AppLayout';

type RecordItem = { id: number; record_type: string; record_number: string; title: string; summary?: string; approved_at?: string; year: number; status: string; issuing_body: string };

export default function Index({ records, filters, canManage }: { records: RecordItem[]; filters: { q: string; type: string }; canManage: boolean }) {
    const [q, setQ] = useState(filters.q || '');
    const search = () => router.get('/legislation', { q, type: filters.type || undefined }, { preserveState: true, replace: true });
    return <AppLayout title="Legislative Records"><div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Central legislative repository</div><h1 className="mt-2 text-3xl font-bold text-slate-950">Ordinances & Resolutions</h1><p className="mt-2 text-sm text-slate-500">Search municipal legislative records from one controlled repository.</p></div>{canManage && <Link href="/legislation/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0b2852] px-4 py-3 text-sm font-semibold text-white"><Plus size={17} /> Add record</Link>}</div><div className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><Search className="ml-2 mt-2.5 text-slate-400" size={19} /><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && search()} className="min-w-0 flex-1 border-0 px-2 py-2 outline-none" placeholder="Search by number, title, subject, or keyword" /><button onClick={search} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Search</button></div><div className="flex flex-wrap gap-2">{[['', 'All'], ['ordinance', 'Ordinances'], ['resolution', 'Resolutions'], ['executive_order', 'Executive Orders']].map(([value, label]) => <button key={value} onClick={() => router.get('/legislation', { q: q || undefined, type: value || undefined }, { preserveState: true })} className={`rounded-full px-4 py-2 text-sm font-semibold ${filters.type === value || (!filters.type && !value) ? 'bg-blue-800 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{label}</button>)}</div><div className="divide-y divide-slate-100 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{records.map((record) => <Link key={record.id} href={`/legislation/${record.id}`} className="flex flex-col gap-4 px-6 py-5 transition hover:bg-blue-50/40 md:flex-row md:items-center md:justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-blue-700">{record.record_number}</div><div className="mt-1 text-lg font-semibold text-slate-950">{record.title}</div><div className="mt-1 text-sm text-slate-500">{record.record_type.replaceAll('_', ' ')} · {record.year} · {record.issuing_body}</div></div><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold uppercase text-emerald-800">{record.status}</span><ArrowRight size={18} className="text-slate-400" /></div></Link>)}{records.length === 0 && <div className="p-12 text-center text-sm text-slate-500">No legislative records matched the search.</div>}</div></div></AppLayout>;
}
