import { useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import AppLayout from '../../layouts/AppLayout';

type Agenda = { id: number; sequence_no: number; title: string; status: string; transaction?: { reference_no: string; title: string } | null; legislative_record?: { record_number: string; title: string } | null };
type Session = { id: number; session_code: string; session_type: string; title: string; scheduled_at: string; location?: string | null; status: string; agenda_items: Agenda[] };
type Work = { id: number; reference_no: string; title: string; status: string; priority: string; due_at?: string | null; current_department?: { short_name?: string | null; name: string } | null };

export default function Workspace({ sessions, legislativeWork }: { sessions: Session[]; legislativeWork: Work[] }) {
    const form = useForm({ session_code: '', session_type: 'regular', title: '', scheduled_at: '', location: '', notes: '' });
    const submit = (e: FormEvent) => { e.preventDefault(); form.post('/legislative-workspace/sessions', { preserveScroll: true, onSuccess: () => form.reset() }); };
    return <AppLayout title="Legislative Workspace"><div className="mx-auto max-w-7xl space-y-6">
        <section className="rounded-3xl bg-[#0b2852] p-6 text-white sm:p-8"><div className="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">Phase 1 · M9</div><h1 className="mt-3 text-3xl font-bold">Vice Mayor & Sangguniang Bayan Workspace</h1><p className="mt-2 text-sm text-blue-100">Session scheduling, agenda control, legislative work queue, calendar publication, and cross-branch routed work.</p></section>
        <section className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Schedule session</h2><div className="mt-4 grid gap-3"><input required placeholder="Session code" value={form.data.session_code} onChange={e => form.setData('session_code', e.target.value)} className="rounded-xl border p-2.5 text-sm"/><select value={form.data.session_type} onChange={e => form.setData('session_type', e.target.value)} className="rounded-xl border p-2.5 text-sm"><option value="regular">Regular</option><option value="special">Special</option><option value="committee">Committee</option><option value="other">Other</option></select><input required placeholder="Title" value={form.data.title} onChange={e => form.setData('title', e.target.value)} className="rounded-xl border p-2.5 text-sm"/><input required type="datetime-local" value={form.data.scheduled_at} onChange={e => form.setData('scheduled_at', e.target.value)} className="rounded-xl border p-2.5 text-sm"/><input placeholder="Location" value={form.data.location} onChange={e => form.setData('location', e.target.value)} className="rounded-xl border p-2.5 text-sm"/><button className="rounded-xl bg-[#0b2852] px-4 py-2.5 text-sm font-semibold text-white">Schedule</button></div></form><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Legislative routed work</h2><div className="mt-4 space-y-2">{legislativeWork.map(w => <a key={w.id} href={`/transactions/${w.id}`} className="block rounded-xl bg-slate-50 p-3 text-sm"><div className="font-semibold">{w.reference_no} · {w.title}</div><div className="mt-1 text-xs text-slate-500">{w.current_department?.short_name || w.current_department?.name} · {w.status.replaceAll('_',' ')} · {w.priority}</div></a>)}</div></div></section>
        <section className="space-y-3">{sessions.map(s => <div key={s.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs font-bold uppercase text-blue-700">{s.session_code} · {s.session_type}</div><h2 className="mt-1 text-lg font-bold">{s.title}</h2></div><div className="text-xs text-slate-500">{new Date(s.scheduled_at).toLocaleString()} · {s.status}</div></div><div className="mt-4 space-y-2">{s.agenda_items.map(a => <div key={a.id} className="rounded-xl bg-slate-50 p-3 text-sm"><span className="font-bold">{a.sequence_no}.</span> {a.title}<div className="mt-1 text-xs text-slate-500">{a.transaction?.reference_no || a.legislative_record?.record_number || 'Internal agenda item'} · {a.status}</div></div>)}</div></div>)}</section>
    </div></AppLayout>;
}
